// DRAWER ACTION TYPES
export const TOGGLE_LEFT_DRAWER = 'TOGGLE_LEFT_DRAWER';
export const TOGGLE_RIGHT_DRAWER = 'TOGGLE_RIGHT_DRAWER';
export const SET_RIGHT_NAV_TAB_VALUE = 'SET_RIGHT_NAV_TAB_VALUE';

// LOADING ACTION TYPE
export const SET_LOADING = 'SET_LOADING';
